version: "3"

services:
  db:
    image: postgres:12
    restart: always
    env_file: ../env-production.env
    sysctls:
      net.core.somaxconn: 65535
    environment:
      PGDATA: '/var/lib/postgres/data'
    volumes:
      - ../postgres-data:/var/lib/postgres/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    sysctls:
      net.core.somaxconn: 65535
    ports:
      - '6379:6379'
    volumes:
      - ../redis-data:/var/lib/redis:rw
    command: redis-server --requirepass MyRedisPasswordVeryStrong

  app:
    build:
      context: ..
      dockerfile: docker-production.dockerfile
    restart: always
    sysctls:
      net.core.somaxconn: 65535
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
      - ../uwsgi:/etc/uwsgi
      - ../media:/app/media
      - ../static:/app/static
      - ../logs:/app/logs
      - ../scripts/docker-entrypoint.sh:/app/scripts/docker-entrypoint.sh

    env_file: ../env-develop.env
    command: /app/scripts/docker-entrypoint.sh
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  nginx:
    image: nginx:latest
    restart: always
    sysctls:
      net.core.somaxconn: 65535
    depends_on:
      - app
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/project.conf:/etc/nginx/conf.d/project.conf
      - ../nginx/certs/selfsigned.crt:/etc/nginx/selfsigned.crt
      - ../nginx/certs/selfsigned.key:/etc/nginx/selfsigned.key
      - ../media:/var/www/media
      - ../static:/var/www/static
      - ../logs:/var/log/nginx
    links:
      - app

